ManPowerSols/Areas/Employer/Controllers/EmpDashboardController.cs
using ManPowerSols.Core;
using ManPowerSols.Core.Models;
using ManPowerSols.Data;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace ManPowerSols.Areas.Employer.Controllers
{
    public class EmpDashboardController : Controller
    {
        // GET: Employer/EmpDashboard
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ChangePassword()
        {
            //ViewBag.ResponseCode = null;
            //ViewBag.ResponseMessage = null;
            return View();
        }
        public ActionResult MyProfile()
        {
            return View();
        }
        public ActionResult ProfileUpdate()
        {
            return View();
        }
        public ActionResult MyDeals()
        {
            return View();
        }
        public ActionResult UserDeals()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ChangePassword(FormCollection frm)
        {
            ChangePasswordModel cpm = new ChangePasswordModel();
            MainRepoistory mps = new MainRepoistory();
            try
            {
                cpm.userid = frm["txtuserid"];
                cpm.usertype = frm["txtusertype"];
                cpm.password = frm["txtcurrentpwd"];
                cpm.newpassword = frm["txtnewpwd"];
                string res = mps.ChangePassword(cpm);
                JavaScriptSerializer json_serializer = new JavaScriptSerializer();
                var finalres = JsonConvert.DeserializeObject<ChangePasswordResult>(res);
                TempData["ResponseCode"] = finalres.ResponseCode;
                TempData["ResponseMessage"] = finalres.ResponseMessage;
            }
            catch (Exception ex)
            {
                ErrorWriter.WriteLog(ex.GetType().ToString(), ex.GetType().Name.ToString(), ex.InnerException.ToString(), "ChangePassword", "UserDashboardController");
            }
            return Redirect("/User/UserDashboard/ChangePassword");
        }
    }
   
}

ManPowerSols/Areas/Employer/Views/EmpDashboard/ChangePassword.cshtml
@using ManPowerSols.Core.Models
@{
    ViewBag.Title = "ChangePassword";
    Layout = "~/Views/Shared/_EmployerLayout.cshtml";
}

<div class="az-content-body">
    <div class="row row-sm">
        <div class="col-xl-9 mg-t-20">
            <div class="card card-dashboard-twentyone">
                <div class="row no-gutters">
                    <div class="col-md-12">
                        <div class="card-body">
                             <h3 class="">Change Password</h3> 
                            <hr>
                            <div class="modal-body pd-sm-40" style="padding:0 20px">
                              
                                @if (TempData["ResponseCode"] != null)
                                {
                                    if (TempData["ResponseCode"].ToString() == "200")
                                    {
                                    <div class="alert alert-success">
                                        <strong>Success!</strong> @TempData["ResponseMessage"].ToString()
                                    </div>
                                    }
                                    else if (TempData["ResponseCode"].ToString() != "200")
                                    {
                                    <div class="alert alert-danger">
                                        <strong>Error!</strong> @TempData["ResponseMessage"].ToString()
                                    </div>
                                    }
                                }
                                <form id="frmsrc" method="post" name="frmsrc" action="/EmpDashboard/ChangePassword">
                                    @*@using (@Html.BeginForm("ChangePassword", "EmpDashboard", FormMethod.Post)){*@
                                    <input type="hidden" class="form-control" id="txtusertype" name="txtusertype">
                                    <input type="hidden" class="form-control" id="txtuserid" name="txtuserid">
                                    <div class="form-group">
                                        <input type="password" class="form-control" placeholder="Current Password" id="txtcurrentpwd" name="txtcurrentpwd" required="required">
                                    </div><!-- form-group -->
                                    
                                    <div class="form-group">
                                        <input type="password" class="form-control" placeholder="New Password" id="txtnewpwd" name="txtnewpwd" required="required">
                                    </div><!-- form-group -->
                                    <div class="form-group">
                                        <input type="password" class="form-control" placeholder="Confirm Password" id="txtconfpwd" name="txtconfpwd" />
                                    </div><!-- form-group -->
                                    <button class="btn btn-primary" id="btnchangepwd" type="submit">Change Password</button>
                                </form>
                              @*}*@
                            </div>
                        </div>
                    </div>
                </div><!-- row -->
            </div><!-- card -->
        </div><!-- col -->
    </div><!-- row -->
</div>

<script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>
<script src="~/MpsJs/CommonJs.js"></script>
<script>
    $("form[name='frmsrc']").validate({
        // Specify validation rules
        rules: {
            txtcurrentpwd: "required",
            txtnewpwd: {
                required: true,
                minlength: 5
            },
            txtconfpwd: {
                required: true,
                equalTo: "#txtnewpwd"
            },
        },

        submitHandler: function (form) {
            form.submit();
        },
        errorPlacement: function (error, element) {
            var placement = $(element).data('error');
            if (placement) {
                $(placement).append(error)
            } else {
                error.insertAfter(element);
            }
        }
    });
    $('#btnchangepwd').click(function (e) {
        if (form.valid() == true) {
            e.preventDefault();
        }
    })
    $(document).ready(function(){
        $('#txtusertype').val(sessionStorage.getItem('usertype'));
        $('#txtuserid').val(sessionStorage.getItem('usermailid'));
    })
</script>

ManPowerSols/Areas/Employer/Views/EmpDashboard/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_EmployerLayout.cshtml";
}


<script src="~/MpsJs/CommonJs.js"></script>

<div class="nav-wrapper">
    <nav class="nav az-nav-line">
        <a href="#" class="nav-link active">Overview</a>
        @*<a href="#" class="nav-link">Deals</a>
        <a href="#" class="nav-link">Reviews</a>
        <a href="#" class="nav-link">Notifications</a>*@
    </nav>
</div>

<div class="az-content-body">

    <div class="row row-sm">
        <div class="col-sm-6 col-xl-3">
            <div class="card card-dashboard-twentytwo">
                <div class="media">
                    <div class="media-icon bg-purple"><i class="typcn typcn-chart-line-outline"></i></div>
                    <div class="media-body">
                        <h6>32.53% <small class="down">-0.5%</small></h6>
                        <span>Admin Request</span>
                    </div>
                </div>
                <div class="chart-wrapper">
                    <div id="flotChart1" class="flot-chart" style="padding: 0px; position: relative;"><canvas class="flot-base" width="270" height="120" style="direction: ltr; position: absolute; left: 0px; top: 0px; width: 270.25px; height: 120px;"></canvas><canvas class="flot-overlay" width="270" height="120" style="direction: ltr; position: absolute; left: 0px; top: 0px; width: 270.25px; height: 120px;"></canvas></div>
                </div><!-- chart-wrapper -->
            </div><!-- card -->
        </div><!-- col -->
        <div class="col-sm-6 col-xl-3 mg-t-20 mg-sm-t-0">
            <div class="card card-dashboard-twentytwo">
                <div class="media">
                    <div class="media-icon bg-primary"><i class="typcn typcn-chart-line-outline"></i></div>
                    <div class="media-body">
                        <h6>7,682 <small class="up">+0.1%</small></h6>
                        <span>Agents Request</span>
                    </div>
                </div>
                <div class="chart-wrapper">
                    <div id="flotChart2" class="flot-chart" style="padding: 0px; position: relative;"><canvas class="flot-base" width="270" height="120" style="direction: ltr; position: absolute; left: 0px; top: 0px; width: 270.25px; height: 120px;"></canvas><canvas class="flot-overlay" width="270" height="120" style="direction: ltr; position: absolute; left: 0px; top: 0px; width: 270.25px; height: 120px;"></canvas></div>
                </div><!-- chart-wrapper -->
            </div><!-- card -->
        </div><!-- col-3 -->
        <div class="col-sm-6 col-xl-3 mg-t-20 mg-xl-t-0">
            <div class="card card-dashboard-twentytwo">
                <div class="media">
                    <div class="media-icon bg-pink"><i class="typcn typcn-chart-line-outline"></i></div>
                    <div class="media-body">
                        <h6>5 <small class="down">Today</small></h6>
                        <span>Users Requests				  </span>
                    </div>
                </div>
                <div class="chart-wrapper">
                    <div id="flotChart3" class="flot-chart" style="padding: 0px; position: relative;"><canvas class="flot-base" width="270" height="120" style="direction: ltr; position: absolute; left: 0px; top: 0px; width: 270.25px; height: 120px;"></canvas><canvas class="flot-overlay" width="270" height="120" style="direction: ltr; position: absolute; left: 0px; top: 0px; width: 270.25px; height: 120px;"></canvas></div>
                </div><!-- chart-wrapper -->
            </div><!-- card -->
        </div><!-- col -->

        <div class="col-xl-9 mg-t-20">
            <div class="card card-dashboard-twentyone">
                <div class="row no-gutters" style="height:500px">


                </div><!-- row -->
            </div><!-- card -->
        </div><!-- col -->
        <div class="col-md-4 col-xl-3 mg-t-20">
            <div class="card card-body card-dashboard-twentythree ht-xl-100p">
                <h6 class="card-title tx-14 mg-b-10">Manage Deals</h6>
                <p class="mg-b-15">The percentage of manages the Agents request and U posting.</p>

                <div class="d-flex flex-column align-items-center mg-b-25">
                    <div>
                        <div class="az-donut-chart chart1">
                            <div class="slice one"></div>
                            <div class="slice two"></div>
                            <div class="chart-center">
                                <span></span>
                            </div>
                        </div>
                    </div>
                </div><!-- d-flex -->

                <div class="row row-sm">
                    <div class="col-6">
                        <label><span class="bg-indigo"></span> Agents</label>
                        <h5>67%</h5>
                    </div>
                    <div class="col-6">
                        <label><span class="bg-gray-500"></span> Users</label>
                        <h5>89%</h5>
                    </div>
                </div><!-- row -->
            </div>
        </div>
    </div><!-- row -->
</div>

ManPowerSols/Areas/Employer/Views/EmpDashboard/MyDeals.cshtml
@{
    ViewBag.Title = "MyDeals";
    Layout = "~/Views/Shared/_EmployerLayout.cshtml";
}


<div class="">
    <div class="az-content-body">
        <div class="row row-sm">
            <div class="col-xl-12 mg-t-20">
                <div class="card card-dashboard-twentyone">
                    <div class="row no-gutters">
                        <div class="col-md-12">
                            <!--Div To show the dta grid-->
                            <div class="card-body" id="divJobsgrid">
                                <!-- <h6 class="az-content-label">My Profile</h6> -->
                                <p>My Job Deals</p>
                                <hr class="">
                                <div class="modal-body pd-sm-40" style="padding:0 20px">
                                    <div>
                                        <div class="form-group" data-select2-id="8">
                                            <table id="example2" class="table"></table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div><!-- row -->
                    </div><!-- card -->
                </div><!-- col -->
            </div><!-- row -->
        </div><!-- az-content-body -->
        <!-- az-footer -->
    </div><!-- az-content -->
</div>

<script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>

<script src="~/lib/perfect-scrollbar/perfect-scrollbar.min.js"></script>
<script src="~/lib/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="~/lib/datatables.net-dt/js/dataTables.dataTables.min.js"></script>
<script src="~/lib/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
<script src="~/lib/datatables.net-responsive-dt/js/responsive.dataTables.min.js"></script>


<script src="~/MpsJs/CommonJs.js"></script>

<script>
     var dataSet = []
     $(document).ready(function () {
         getuserdeals()
     })
     function getuserdeals() {
         dataSet = [];
         $.ajax({
             url: '/User/UserDashboard/GetUserAppliedJobs',
             type: 'GET',
             data: { 'usrid': sessionStorage.getItem('usermailid') },
             contentType: 'application/json; charset=utf-8',
             dataType: "json",
             success: function (res) {
                 if (res.ResponseCode == "200") {
                     bindjobsdata(res.ResponseList.joblist)
                 }

                 else {
                     bindjobsdata(dataSet)
                 }

             },
             error: function (err) {
                 bindjobsdata(dataSet)
             }
         });
     }
     //Function used to bind the data to data table
     var table;
     function bindjobsdata(res) {
         var url = window.location.href.split('/')[0]
         for (var i = 0; i < res.length; i++) {
             //var act = '<img src="' + url + '/img/edit.png" style="cursor:pointer">&nbsp;&nbsp;<img src="' + url + '/img/delete.png" onclick="deleteJob(\'' + res[i].Rec_ID + '\',\'N\')" style="cursor:pointer">'
             dataSet[i] = [
                 //'<a href="#" style="cursor:pointer" onclick="jobfulldetails(\'' + res[i].Rec_ID + '\')">' + res[i].Post_Title + '</a>',
                 res[i].Post_Title,
                            res[i].CompanyName,
                            res[i].NoOfEmp + ' Nos',

                            res[i].Access_status,
                            //res[i].FromTime + ' - ' + res[i].ToTime,
                            res[i].JobAppliedDate,
                            res[i].Country,
                            //act
             ]
         }
         //console.log(dataSet)
         table = $('#example2').DataTable({
             destroy: true,
             responsive: true,
             language: {
                 searchPlaceholder: 'Search...',
                 sSearch: '',
                 lengthMenu: '_MENU_ items/page',
             },
             data: dataSet,
             columns: [
                 { title: "Job Title" },
             { title: "Company Name" },
             { title: "Vacancies" },
              { title: "Status" },
            // { title: "Timings" },

             { title: "Appllied On", },
             { title: "Location", },
               //{ title: "Action", },
             ],
             buttons: {
                 buttons: [
                     {
                         text: 'Alert',
                         action: function (e, dt, node, config) {
                             //alert('Activated!');
                             this.disable(); // disable button
                         }
                     }
                 ]
             }
         });
     }
</script>

ManPowerSols/Areas/Employer/Views/EmpDashboard/MyProfile.cshtml
@{
    ViewBag.Title = "MyProfile";
    Layout = "~/Views/Shared/_EmployerLayout.cshtml";
}

<div class="progress mg-b-10" style="width:25%">
    <div class="progress-bar progress-bar-lg wd-50p" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100">50%</div>
</div>
<div class="az-content-body" id="divprofile">
    <div class="row row-sm">
        <div class="col-xl-12">
            <div class="card card-dashboard-twentyone">
                <div class="row no-gutters">
                    <div class="col-md-12">
                        <div class="card-body">
                            <!-- <h6 class="az-content-label">My Profile</h6> -->
                            <div class="az-profile-overview">
                                <div class="" style="float:left">
                                    <img src="~/img/img10.jpg" id="profileimg" alt="Profile Image" style="height:60px;width:60px;">
                                </div><!-- az-img-user -->
                                <div style="float:right">
                                    <h5 class="az-profile-name" id="txtname"></h5>
                                    <p class="az-profile-name-text" id="txtdesignation"></p>
                                </div>
                                <br /><br />
                                <div class="d-flex justify-content-between mg-b-20">

                                    <div class="btn-icon-list" style="display:none">
                                        <button class="btn btn-indigo btn-icon"><i class="typcn typcn-plus-outline"></i></button>
                                        <button class="btn btn-primary btn-icon"><i class="typcn typcn-message"></i></button>
                                    </div>
                                </div>
                                <div class="" id="txtaboutme">
                                </div><!-- az-profile-bio -->
                                <hr class="">
                                <label class="az-content-label tx-13 mg-b-20">Personal Details</label>
                                <div class="az-profile-social-list">
                                    <div class="media">
                                        <div class="media-icon"><i class="icon ion-logo-github"></i></div>
                                        <div class="media-body">
                                            <span id="spanname"></span>
                                            <a href="#" id="txtdesgcompany"></a>
                                        </div>
                                    </div><!-- media -->
                                    <div class="media">
                                        <div class="media-icon"><i class="icon ion-logo-twitter"></i></div>
                                        <div class="media-body">
                                            <span>Email</span>
                                            <a href="#" id="txtemail">info@manpowersupplier.net</a>

                                        </div>
                                    </div><!-- media -->
                                    <div class="media">
                                        <div class="media-icon"><i class="icon ion-logo-linkedin"></i></div>
                                        <div class="media-body">
                                            <span>Phone</span>
                                            <a href="#" id="txtmobile"></a>
                                            <a href="#" id="txtmobile2" style="display:block"></a>
                                        </div>
                                    </div><!-- media -->
                                </div><!-- az-profile-social-list -->

                            </div>
                            <hr class="mg-y-40">
                            <div class="row">
                                <div class="col-md-7 col-xl-8" style="display:block">
                                    <div class="az-content-label tx-13 mg-b-25">Work &amp; Experience</div>
                                    <div class="az-profile-work-list">
                                        <div class="media">
                                            <div class="media-logo bg-success"><i class="icon ion-logo-buffer"></i></div>
                                            <div class="media-body">
                                                <h6 id="txtdesignation2"></h6> at <a href="#" id="txtcompany"></a>
                                                <label id="txtperiodofworking"></label> in <span id="txtcategory"></span> with <label id="txtexp"></label> of experience.
                                                <p id="txtsalary"></p>
                                            </div><!-- media-body -->
                                        </div><!-- media -->

                                    </div><!-- az-profile-work-list -->
                                </div><!-- col -->
                                <div class="col-md-5 col-xl-4 mg-t-40 mg-md-t-0">
                                    <div class="az-content-label tx-13 mg-b-25">Contact Information</div>
                                    <div class="az-profile-contact-list">
                                        <div class="media">
                                            <div class="media-icon"><i class="icon ion-md-phone-portrait"></i></div>
                                            <div class="media-body">
                                                <span>Mobile</span>
                                                <div id="divmobile"></div>
                                            </div><!-- media-body -->
                                        </div><!-- media -->
                                        <div class="media">
                                            <div class="media-icon"><i class="icon ion-md-locate"></i></div>
                                            <div class="media-body">
                                                <span>Current Address</span>
                                                <div id="divaddress"></div>
                                            </div><!-- media-body -->
                                        </div><!-- media -->
                                    </div><!-- az-profile-contact-list -->
                                </div><!-- col -->
                            </div>
                            <br />
                            <a href="../EmpDashboard/ProfileUpdate" class="btn-xs btn-primary" style="padding:5px" id="btneditprofile">
                                <img src="~/img/edit.png" style="cursor:pointer">
                                Edit Profile
                            </a>
                            <hr class="mg-y-40">
                        </div>
                    </div>

                </div><!-- row -->
            </div><!-- card -->
        </div><!-- col -->
        <div class="col-md-4 col-xl-3 mg-t-20" style="display:none">
            <div class="card card-body card-dashboard-twentythree ht-xl-100p">
                <h6 class="card-title tx-14 mg-b-10">Manage Deals</h6>
                <p class="mg-b-15">The percentage of manages the empoloyers request and agents posting.</p>

                <div class="d-flex flex-column align-items-center mg-b-25">
                    <div>
                        <div class="az-donut-chart chart1">
                            <div class="slice one"></div>
                            <div class="slice two"></div>
                            <div class="chart-center">
                                <span></span>
                            </div>
                        </div>
                    </div>
                </div><!-- d-flex -->

                <div class="row row-sm">
                    <div class="col-6">
                        <label><span class="bg-indigo"></span> Employers</label>
                        <h5>67%</h5>
                    </div>
                    <div class="col-6">
                        <label><span class="bg-gray-500"></span> Agents</label>
                        <h5>89%</h5>
                    </div>
                </div><!-- row -->
            </div>
        </div>
    </div><!-- row -->
</div>

<script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="~/MpsJs/CommonJs.js"></script>
<script>
    $(document).ready(function () {
        getUserprofile(sessionStorage.getItem("usermailid"))
    })

    function getUserprofile(userid) {
        var up = {};
        up.UserID = userid;
        //up.UserID = 'prpdevobal@gmail.com';
        $.ajax({
            url: '/UserDashboard/GetUserProfile',
            type: 'POST',
            data: JSON.stringify(up),
            contentType: 'application/json; charset=utf-8',
            dataType: "json",
            success: function (res) {
                if (res.ResponseCode == "200") {
                    //$('.hdncls').show();
                    bindProfile(res.ResponseList.userdetails)
                }
                else if (res.ResponseCode == "201") {
                    bindProfile(res.ResponseList.userdetails)
                    //$('.hdncls').hide();
                }
                else if (res.ResponseCode == "100") {
                    alert('something went wrong! Please try again.')
                }
                else {
                    alert('Error : Status Code: ' + res.ResponseCode + '. Messsage' + res.ResponseMessage)
                }
            },
            error: function (err) {

            }
        });
    }

    function bindProfile(data) {
        $('#txtuserid').text(data[0].UserID);
        $('#txtrecid').text(data[0].Rec_ID);
        $('#txtname,#spanname').text(data[0].FirstName + ' ' + data[0].LastName);
        $('#txtdesignation').html(data[0].Designation == null ? '' : data[0].Designation);
        $('#txtaboutme').text(data[0].AboutMe == null ? '' : data[0].AboutMe);
        $('#txtdesgcompany').text(data[0].Designation == null ? '' : data[0].Designation + '-' + data[0].PresentCompanyName == null ? '' : data[0].PresentCompanyName)
        $('#txtemail').text(data[0].Email);
        $('#txtmobile,#divmobile').text(data[0].Mobile);
        $('#txtmobile2').text(data[0].Altenative_mobile == null ? '' : data[0].Altenative_mobile);
        $('#divaddress').text(data[0].City == null ? '' : data[0].City + ', ' + data[0].State == null ? '' : data[0].State + ', ' + data[0].Country == null ? '' : data[0].Country + ' - ' + data[0].zipcode == null ? '' : data[0].zipcode);
        $('#txtcompany').text(data[0].PresentCompanyName == null ? '' : data[0].PresentCompanyName);
        $('#txtdesignation2').text(data[0].Designation == null ? '' : data[0].Designation)
        $('#txtperiodofworking').text(data[0].PeriodOfWorking == null ? '' : data[0].PeriodOfWorking);
        $("#txtcategory").text(data[0].Work_Sector == null ? '' : data[0].Work_Sector);
        $('#txtexp').text(data[0].Experience == null ? '' : data[0].Experience);
        $('#txtsalary').text('Salary: '+data[0].CurrencyType == '' ? 'N/A' : data[0].CurrencyType.split('-')[0] + '' + data[0].Last_Salary + '-' + data[0].CurrencyType.split('-')[1]);
        //console.log(data[0].Resume=null?'':data[0].Resume)
        //alert(data[0].ImgPath)
        //$('#divresumecontent').html(data[0].Resume);
        
        $('#profileimg').attr('src', data[0].ImgPath == '' || data[0].ImgPath == null ? 'http://mps.manpowersupplier.net/img/admin.png' : data[0].ImgPath)
    }

</script>